import React from "react";
import CMS from "netlify-cms-app";

// Import main site styles as a string to inject into the CMS preview pane
import styles from "!to-string-loader!css-loader!postcss-loader!sass-loader!../css/main.css";

import Ovodai_AaPreview from "./cms-preview-templates/ovodai_aa";
import Ovodai_BPreview from "./cms-preview-templates/ovodai_b";
import Ovodai_CcsPreview from "./cms-preview-templates/ovodai_ccs";
import Ovodai_DPreview from "./cms-preview-templates/ovodai_d";
import Ovodai_EePreview from "./cms-preview-templates/ovodai_ee";
import Ovodai_FPreview from "./cms-preview-templates/ovodai_f";
import Ovodai_GgyPreview from "./cms-preview-templates/ovodai_ggy";
import Ovodai_HPreview from "./cms-preview-templates/ovodai_h";
import Ovodai_IPreview from "./cms-preview-templates/ovodai_i";
import Ovodai_KPreview from "./cms-preview-templates/ovodai_k";
import Ovodai_LPreview from "./cms-preview-templates/ovodai_l";
import Ovodai_MPreview from "./cms-preview-templates/ovodai_m";
import Ovodai_NnyPreview from "./cms-preview-templates/ovodai_nny";
import Ovodai_OoPreview from "./cms-preview-templates/ovodai_oo";
import Ovodai_PPreview from "./cms-preview-templates/ovodai_p";
import Ovodai_RPreview from "./cms-preview-templates/ovodai_r";
import Ovodai_SszPreview from "./cms-preview-templates/ovodai_ssz";
import Ovodai_TPreview from "./cms-preview-templates/ovodai_t";
import Ovodai_UuPreview from "./cms-preview-templates/ovodai_uu";
import Ovodai_VPreview from "./cms-preview-templates/ovodai_v";
import Ovodai_ZzsPreview from "./cms-preview-templates/ovodai_zzs";
import ArakPreview from "./cms-preview-templates/arak";
import AjanlatkeresPreview from "./cms-preview-templates/ajanlatkeres";

CMS.registerPreviewStyle(styles, { raw: true });
CMS.registerPreviewTemplate("ovodai_aa", Ovodai_AaPreview);
CMS.registerPreviewTemplate("ovodai_b", Ovodai_BPreview);
CMS.registerPreviewTemplate("ovodai_ccs", Ovodai_CcsPreview);
CMS.registerPreviewTemplate("ovodai_d", Ovodai_DPreview);
CMS.registerPreviewTemplate("ovodai_ee", Ovodai_EePreview);
CMS.registerPreviewTemplate("ovodai_f", Ovodai_FPreview);
CMS.registerPreviewTemplate("ovodai_ggy", Ovodai_GgyPreview);
CMS.registerPreviewTemplate("ovodai_h", Ovodai_HPreview);
CMS.registerPreviewTemplate("ovodai_i", Ovodai_IPreview);
CMS.registerPreviewTemplate("ovodai_k", Ovodai_KPreview);
CMS.registerPreviewTemplate("ovodai_l", Ovodai_LPreview);
CMS.registerPreviewTemplate("ovodai_m", Ovodai_MPreview);
CMS.registerPreviewTemplate("ovodai_nny", Ovodai_NnyPreview);
CMS.registerPreviewTemplate("ovodai_oo", Ovodai_OoPreview);
CMS.registerPreviewTemplate("ovodai_p", Ovodai_PPreview);
CMS.registerPreviewTemplate("ovodai_r", Ovodai_RPreview);
CMS.registerPreviewTemplate("ovodai_ssz", Ovodai_SszPreview);
CMS.registerPreviewTemplate("ovodai_t", Ovodai_TPreview);
CMS.registerPreviewTemplate("ovodai_uu", Ovodai_UuPreview);
CMS.registerPreviewTemplate("ovodai_v", Ovodai_VPreview);
CMS.registerPreviewTemplate("ovodai_zzs", Ovodai_ZzsPreview);
CMS.registerPreviewTemplate("arak", ArakPreview);
CMS.registerPreviewTemplate("ajanlatkeres", AjanlatkeresPreview);
CMS.init();
